Announce first player to complete an achievement
Warzone/mars pull request #26
Opened 2024-07-08 04:05 UTC by Mew2K

2024-07-08 04:18 UTC, chatasma requested changes

2024-07-08 04:18 UTC, chatasma commented on src/main/kotlin/network/warzone/mars/player/achievements/AchievementEmitter.kt
> +        if (achievement.firstCompletion.toString() == "00000000-0000-0000-0000-000000000000") {
Mentioned in API review but should do a null check instead of checking for an empty UUID

2024-07-08 04:18 UTC, chatasma commented on src/main/kotlin/network/warzone/mars/player/achievements/AchievementManager.kt
> +    fun fetchNewAchievements() {
Doesn't look necessary

2024-07-08 17:29 UTC, Mew2K commented
In addition to the PR Fixes, I've implemented the following mechanisms:
- Hovering over an earned achievement displays it's description.
- Earning an achievement plays a sound.

2024-07-13 03:49 UTC, chatasma approved these changes

2024-07-13 03:49 UTC, merged